parallel-jobs = 1
patches-version = "dev"
enable-magisk-update = false
remove-rv-integrations-checks = true

[spotify-anddea]
enabled = true 
app-name = "spotify"
rv-brand = "anddea"
arch = "both"
patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"
dpi = "120-640dpi 480dpi nodpi anydpi"
apkmirror-durl = "https://www.apkmirror.com/apk/spotify-ab/spotify-music-podcasts"
# archive-dlurl = "https://archive.org/download/geologically/apks/com.spotify.music"



